In [1]:
import numpy as np
import pandas as pd
import torch
import mytools
import mymodels

In [49]:
########################################
########################################
# Select Energy (35 or 50 keV)
Energy = 40
# Select diff amount (H or L)
Diff = 'L'
#Cheat True/False
cheat = False
########################################
########################################

In [50]:
df = pd.read_pickle('tune_NML_'+str(Energy)+'keV_'+Diff+'diff_cheat-'+str(cheat)+'.pk')
df

        wo  n_sigma_L  n_sigma_H      Loss       eff
0     0.04        1.4        2.8 -0.396786  0.993774
1     0.04        1.4        2.9 -0.396848  0.993774
2     0.04        1.4        3.0 -0.393865  0.993774
3     0.04        1.4        3.1 -0.391886  0.993774
4     0.04        1.4        3.2 -0.390440  0.993774
...    ...        ...        ...       ...       ...
2725  0.16        2.7        5.1 -0.626069  0.518253
2726  0.16        2.7        5.2 -0.627981  0.518253
2727  0.16        2.7        5.3 -0.627970  0.518253
2728  0.16        2.7        5.4 -0.628608  0.518253
2729  0.16        2.7        5.5 -0.629542  0.518253

[2730 rows x 5 columns]

In [51]:
print( "wo range: ",  np.min(df.wo), " - ", np.max(df.wo))
print( "n_sigma_L range: ",  np.min(df.n_sigma_L), " - ", np.max(df.n_sigma_L))
print( "n_sigma_H range: ",  np.min(df.n_sigma_H), " - ", np.max(df.n_sigma_H))

wo range:  0.04  -  0.16000000000000003
n_sigma_L range:  1.4  -  2.700000000000001
n_sigma_H range:  2.8  -  5.500000000000002

In [52]:
min1 = df[['Loss']].idxmin()

In [53]:
df.iloc[min1]

        wo  n_sigma_L  n_sigma_H      Loss       eff
2729  0.16        2.7        5.5 -0.629542  0.518253

In [54]:
df.loc[(df.n_sigma_L == 2.700000000000001) & (df.n_sigma_H == 5.200000000000002)]

        wo  n_sigma_L  n_sigma_H      Loss       eff
206   0.04        2.7        5.2 -0.573131  0.518253
416   0.05        2.7        5.2 -0.593893  0.518253
626   0.06        2.7        5.2 -0.605113  0.518253
836   0.07        2.7        5.2 -0.609954  0.518253
1046  0.08        2.7        5.2 -0.615088  0.518253
1256  0.09        2.7        5.2 -0.617120  0.518253
1466  0.10        2.7        5.2 -0.620211  0.518253
1676  0.11        2.7        5.2 -0.622693  0.518253
1886  0.12        2.7        5.2 -0.623581  0.518253
2096  0.13        2.7        5.2 -0.625015  0.518253
2306  0.14        2.7        5.2 -0.626761  0.518253
2516  0.15        2.7        5.2 -0.627097  0.518253
2726  0.16        2.7        5.2 -0.627981  0.518253

In [28]:
Hdiff50T.Loss.to_numpy()[0].item()

-0.653609037399292

In [30]:
np.min(Hdiff50T.Loss)

tensor(-0.7449)